version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-theundercut}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-theundercut}
    ports: ["5432:5432"]
    env_file:
      - .env

  redis:
    image: redis:7
    ports: ["6379:6379"]
