version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: theundercut
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: theundercut
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
