version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: theundercut
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: theundercut
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  # App service configuration example
  # Uncomment and customize as needed
  # web:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgresql+psycopg2://theundercut:secret@db:5432/theundercut
  #     REDIS_URL: redis://redis:6379/0
  #   depends_on:
  #     - db
  #     - redis
