[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "theundercut"
version = "0.0.1"
dependencies = [
  "fastapi==0.111.0",
  "uvicorn[standard]==0.29.0",
  "httpx==0.27.0",
]

# dev extras (tests/lint) will come later
