"""unique lap key

Revision ID: 8587dcdb69dd
Revises: 0adec3d37d25
Create Date: 2025-05-09 22:43:12.901521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8587dcdb69dd'
down_revision: Union[str, None] = '0adec3d37d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_lap_race_driver_lap",
        "lap_times",
        ["race_id", "driver", "lap"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_lap_race_driver_lap", table_name="lap_times")
    # ### end Alembic commands ###
